package constants

const (
	// RepositoryName ...
	RepositoryName = "fusion-build-templates"

	// TemplateRelativePath ...
	TemplateRelativePath = "macos/packer/"

	// UserNameEnv ...
	UserNameEnv = "USERNAME=%s"

	// PasswordEnv ...
	PasswordEnv = "PASSWORD=%s"

	// StoragePathEnv ...
	StoragePathEnv = "STORAGE_PATH=%s"

	// GovcPasswordEnv ...
	GovcPasswordEnv = "GOVC_PASSWORD=%s"

	// GovcInsecureEnv ...
	GovcInsecureEnv = "GOVC_INSECURE=%s"

	// GovcURLEnv ...
	GovcURLEnv = "GOVC_URL=%s"

	// GovcUsernameEnv ...
	GovcUsernameEnv = "GOVC_USERNAME=%s"

	// GovcDataStoreEnv ...
	GovcDataStoreEnv = "GOVC_DATASTORE=%s"

	// GovcDataCenterEnv ...
	GovcDataCenterEnv = "GOVC_DATACENTER=%s"

	// Stdout ...
	Stdout = "stdout"

	// Stderr ...
	Stderr = "stderr"
)
